### ISSUE TITLE
Fetch, parse and evaluate a .houserules config file

### ISSUE THREAD

**Issue by renanivo** [renanivo/houserules#10]
The project should be able to fetch a `.houserules.yml` file from a repository at a given commit. So that we can parse it and evaluate if the rules pass.

Proposed file format:
```yml
add:
  - file1.ext
  - file2.ext

modify:
  - file3.txt
```

Note:
* The `add` and `modify`keys stand for files that, initially, MUST be added or modified, respectively;
* The file patterns should use the [.gitignore syntax](http://git-scm.com/docs/gitignore#_pattern_format).

**Comment by drgarcia1986** [comment]
:+1: 
You think about houserules check some change in the files? some like, don't accept PR with `#FIXME` ?

**Comment by renanivo** [comment]
@drgarcia1986 That would be great. Once I start working on it, I can propose new a file format to handle that.

**Comment by renanivo** [comment]
I was thinking about this file format, and ended up with something inspired by ansible playbook files, eg:

```yml
- name: Don't use let \#FIXME in your code
  rule: '#FIXME' not in item.content
  with: files

- name: WIP commits should be squashed
  rule: 'WIP' not in item.message|upper
  with: commits

- name: Should have at least 2 :+1: comments
  rule: ':+1' in item.content
  with: comments
  times: 2
```

So we can use Jinja to parse it and display the `name` of the failed rule to the user. I'm a little bit concerned with security, though.
